[package]
name = "actix-actors-ping-ponh"
version = "0.1.0"
authors = ["Amidamaru <thao@saito.tech>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.12.0"
actix-rt = "2.6.0"
tokio = "1.5.0"